# Generated by Django 5.2 on 2025-05-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('opcua', 'OPC UA')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_id', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('float', 'Float'), ('string', 'String')], max_length=50)),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='plc.plc')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='plc.sensor')),
            ],
        ),
    ]
